In [14]:
import pandas as pd

movies = pd.read_csv("netflix_cleaned.csv")

In [15]:
movies["genres"].value_counts().reset_index()

                                        genres  count
0                                        Drama   1046
1                                       Comedy    579
2                               Drama, Romance    377
3                                  Documentary    365
4                                Comedy, Drama    296
...                                        ...    ...
2431  Drama, Science Fiction, Fantasy, Romance      1
2432                          Animation, Music      1
2433                    Comedy, Mystery, Drama      1
2434                   Drama, History, Fantasy      1
2435                 Thriller, Romance, Horror      1

[2436 rows x 2 columns]

In [16]:
movies["genres"].value_counts().reset_index().query("count >50")

                       genres  count
0                       Drama   1046
1                      Comedy    579
2              Drama, Romance    377
3                 Documentary    365
4               Comedy, Drama    296
5                      Horror    288
6            Horror, Thriller    277
7             Comedy, Romance    188
8              Romance, Drama    183
9                     Romance    176
10            Drama, Thriller    166
11              Drama, Comedy    162
12           Action, Thriller    138
13             Drama, History    134
14            Romance, Comedy    126
15                   Thriller    124
16     Comedy, Drama, Romance    107
17    Action, Crime, Thriller     89
18            Thriller, Drama     88
19  Horror, Mystery, Thriller     85
20                     Action     77
21           Thriller, Horror     68
22     Crime, Drama, Thriller     67
23            Horror, Mystery     62
24              Action, Drama     59
25             Action, Comedy     57
26     Drama, Comedy, Romance     55
27          Animation, Family     54
28               Crime, Drama     54
29             Comedy, Horror     52
30             Horror, Comedy     52
31    Action, Thriller, Crime     51

In [17]:
category_mapping = {
    'Drama': 'Fiction',
    'Comedy': 'Fiction',
    'Documentary': 'Nonfiction',
    'Reality': 'Nonfiction',
    'Crime': 'Fiction',
    'Romance': 'Fiction',
    'Horror': 'Fiction',
    'Thriller': 'Fiction',
    'Animation': 'Fiction',
    'Family': 'Fiction',
    'Action': 'Fiction',
    'Mystery': 'Fiction',
    'History': 'Nonfiction',
    'Sci-Fi & Fantasy': 'Fiction',
    'Soap': 'Fiction',
    'Talk': 'Nonfiction',
}
movies["simple_category"] = movies["genres"].map(category_mapping)

In [18]:
movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue,tagged_description,simple_category
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867,10192 A bored and domesticated Shrek pacts wit...,NaN
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630,"27205 Cobb, a skilled thief who commits corpor...",NaN
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868,"12444 Harry, Ron and Hermione walk away from t...",NaN
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732,"38757 Feisty teenager Rapunzel, who has long a...",NaN
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471,10191 As the son of a Viking leader on the cus...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12448,616846,Movie,Psykopat,"Matthew Hart, Renaldo Samsara","Arifin Putra, Cornelio Sunny, Nana Mirdad, Mar...","Indonesia, United Kingdom, United States of Am...",2025-02-06,2025,3.000,NaN,"Drama, Thriller, Mystery, Horror",id,A famous illusionist challenges four participa...,4.955,1,3.000,0,0,616846 A famous illusionist challenges four pa...,NaN
12449,1424086,Movie,Blood and Stuffing,Ray Brown,"Hariclia Grammenou, Bethany Tickle, Ren, Ray B...",United Kingdom,2025-02-26,2025,0.000,NaN,Horror,en,A young girl plays a violent game after her si...,4.953,0,0.000,0,0,1424086 A young girl plays a violent game afte...,Fiction
12450,1214052,Movie,To a Land Unknown,Mahdi Fleifel,"Mahmood Bakri, Aram Sabbah, Angeliki Papoulia,...","Germany, Saudi Arabia, Qatar, France, Greece, ...",2025-02-14,2025,6.500,NaN,"Drama, Thriller, Crime",ar,The stakes couldn't be higher for displaced Pa...,4.946,2,6.500,0,0,1214052 The stakes couldn't be higher for disp...,NaN
12451,1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,2025-03-13,2025,0.000,NaN,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0,0,1271724 Poignant stories about men and women w...,Fiction
12452,1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2025-02-22,2025,0.000,NaN,"Comedy, Horror",en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0,0,1405742 After a debt-collector finds a portal ...,NaN

In [23]:
movies["country"].value_counts().reset_index().query("count >50")

country_counts = movies['country'].value_counts()

countries_to_keep = country_counts[country_counts > 50].index

movies = movies[movies['country'].isin(countries_to_keep)]

movies['country'].value_counts()

country
United States of America                    4262
Japan                                        708
South Korea                                  661
France                                       499
United Kingdom                               460
United Kingdom, United States of America     318
Canada, United States of America             294
India                                        292
Canada                                       280
Spain                                        205
China                                        170
Italy                                        169
Russia                                       152
Belgium, France                              148
Germany                                      141
Philippines                                  113
Australia                                    109
Mexico                                        94
Brazil                                        87
China, Hong Kong                              75
Hong Kong                                     53
Name: count, dtype: int64

In [24]:
movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue,tagged_description,simple_category
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867,10192 A bored and domesticated Shrek pacts wit...,NaN
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630,"27205 Cobb, a skilled thief who commits corpor...",NaN
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868,"12444 Harry, Ron and Hermione walk away from t...",NaN
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732,"38757 Feisty teenager Rapunzel, who has long a...",NaN
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471,10191 As the son of a Viking leader on the cus...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12445,934456,Movie,Americana,Tony Tost,"Sydney Sweeney, Paul Walter Hauser, Halsey, Si...","Canada, United States of America",2025-08-22,2025,0.000,NaN,"Action, Comedy, Crime",en,When a rare Lakota Ghost Shirt falls into the ...,4.968,0,0.000,0,0,934456 When a rare Lakota Ghost Shirt falls in...,NaN
12446,1254780,Movie,The Grove,"Acoryé White, Patrycja Kępa","Acoryé White, Carl Anthony Payne II, Psalms Sa...",United States of America,2025-04-04,2025,0.000,NaN,"Horror, Thriller, Mystery, Drama",en,"When Terrance, a Black Ops soldier, goes under...",4.963,0,0.000,0,0,"1254780 When Terrance, a Black Ops soldier, go...",NaN
12449,1424086,Movie,Blood and Stuffing,Ray Brown,"Hariclia Grammenou, Bethany Tickle, Ren, Ray B...",United Kingdom,2025-02-26,2025,0.000,NaN,Horror,en,A young girl plays a violent game after her si...,4.953,0,0.000,0,0,1424086 A young girl plays a violent game afte...,Fiction
12451,1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,2025-03-13,2025,0.000,NaN,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0,0,1271724 Poignant stories about men and women w...,Fiction
12452,1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2025-02-22,2025,0.000,NaN,"Comedy, Horror",en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0,0,1405742 After a debt-collector finds a portal ...,NaN

In [25]:
movies[~(movies["simple_category"].isna())]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue,tagged_description,simple_category
15,37799,Movie,The Social Network,David Fincher,"Jesse Eisenberg, Andrew Garfield, Armie Hammer...",United States of America,2010-10-01,2010,7.368,NaN,Drama,en,"In 2003, Harvard undergrad and computer progra...",69.048,12285,7.368,40000000,224920315,"37799 In 2003, Harvard undergrad and computer ...",Fiction
63,44363,Movie,Frozen,Adam Green,"Emma Bell, Shawn Ashmore, Kevin Zegers, Ed Ack...",United States of America,2010-02-05,2010,6.000,NaN,Thriller,en,When three skiers find themselves stranded on ...,30.006,1855,6.000,0,3065860,44363 When three skiers find themselves strand...,Fiction
75,37735,Movie,Easy A,Will Gluck,"Emma Stone, Penn Badgley, Amanda Bynes, Dan By...",United States of America,2010-09-16,2010,6.800,NaN,Comedy,en,"Olive, an average high school student, sees he...",25.329,6963,6.800,8000000,75026327,"37735 Olive, an average high school student, s...",Fiction
103,63319,Movie,Belle épine,Rebecca Zlotowski,"Léa Seydoux, Anaïs Demoustier, Johan Libéreau,...",France,2010-11-10,2010,5.500,NaN,Drama,fr,"After the death of her mother, 17-year-old Pru...",20.789,53,5.500,0,0,"63319 After the death of her mother, 17-year-o...",Fiction
110,65496,Movie,Student Services,Emmanuelle Bercot,"Déborah François, Mathieu Demy, Alain Cauchi, ...",France,2010-01-18,2010,5.300,NaN,Drama,fr,Nineteen-year-old Laura is stressed by her fir...,20.139,125,5.300,0,0,65496 Nineteen-year-old Laura is stressed by h...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12430,1418522,Movie,Delicious,Nele Mueller-Stöfen,"Fahri Yardım, Valerie Pachner, Carla Díaz, Nai...",Germany,2025-02-18,2025,7.000,NaN,Drama,en,A wealthy German family hires a young woman as...,5.113,1,7.000,0,0,1418522 A wealthy German family hires a young ...,Fiction
12433,1437397,Movie,Un an avec Jordan Bardella,"Guillaume Genton, Thibault Gitton, Guillaume G...",Jordan Bardella,France,2025-02-20,2025,6.800,NaN,Documentary,fr,"For over a year, cameras followed Jordan Barde...",5.090,2,6.800,0,0,"1437397 For over a year, cameras followed Jord...",Nonfiction
12442,1309027,Movie,Last Take: Rust and the Story of Halyna,Rachel Mason,Halyna Hutchins,United States of America,2025-03-11,2025,0.000,NaN,Documentary,en,"A personal look at the life, work and untimely...",5.018,0,0.000,0,0,"1309027 A personal look at the life, work and ...",Nonfiction
12449,1424086,Movie,Blood and Stuffing,Ray Brown,"Hariclia Grammenou, Bethany Tickle, Ren, Ray B...",United Kingdom,2025-02-26,2025,0.000,NaN,Horror,en,A young girl plays a violent game after her si...,4.953,0,0.000,0,0,1424086 A young girl plays a violent game afte...,Fiction
12451,1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,2025-03-13,2025,0.000,NaN,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0,0,1271724 Poignant stories about men and women w...,Fiction

In [26]:
from transformers import pipeline
import torch
fiction_categories =["Fiction", "Nonfiction"]

In [27]:
pipe = pipeline("zero-shot-classification",
                model="facebook/bart-large-mnli")

Device set to use cpu

In [28]:
sequence=movies.loc[movies["simple_category"] == "Fiction", "description"].reset_index(drop=True)[0]

In [29]:
pipe(sequence, fiction_categories)

{'sequence': 'In 2003, Harvard undergrad and computer programmer Mark Zuckerberg begins work on a new concept that eventually turns into the global social network known as Facebook. Six years later, Mark is one of the youngest billionaires ever, but his unprecedented success leads to both personal and legal complications when he ends up on the receiving end of two lawsuits, one involving his former friend.',
 'labels': ['Nonfiction', 'Fiction'],
 'scores': [0.6824323534965515, 0.3175675868988037]}

now we are getting the score based on the description whether the movie/tv is fiction or non-fiction

In [30]:
import numpy as np
max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_lable =pipe(sequence, fiction_categories)["labels"][max_index]
max_lable

'Nonfiction'

creating function for all the data

In [33]:
def generate_predictions(sequence,categories):
    predictions =pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_lable = predictions["labels"][max_index]
    return max_lable

Evaluating the zero shot model on how accurate the prediction is by comparing to know lables

In [34]:
from tqdm import tqdm

actual_cats =[]
predicted_cats =[]

for i in tqdm(range(0, 300)):
    sequence = movies.loc[movies["simple_category"] == "Fiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Fiction"]

100%|██████████| 300/300 [06:33<00:00,  1.31s/it]

In [38]:
for i in tqdm(range(0, 200)):
    sequence = movies.loc[movies["simple_category"] == "Nonfiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Nonfiction"]

100%|██████████| 200/200 [03:47<00:00,  1.14s/it]

In [39]:
predictions_df =pd.DataFrame({"actual_category":actual_cats,"predicted_category":predicted_cats})

In [40]:
predictions_df

     actual_category predicted_category
0            Fiction         Nonfiction
1            Fiction         Nonfiction
2            Fiction         Nonfiction
3            Fiction            Fiction
4            Fiction            Fiction
...              ...                ...
1071      Nonfiction         Nonfiction
1072      Nonfiction         Nonfiction
1073      Nonfiction         Nonfiction
1074      Nonfiction         Nonfiction
1075      Nonfiction         Nonfiction

[1076 rows x 2 columns]

In [41]:
predictions_df["correct_prediction"] = (
    np.where(predictions_df["actual_category"] == predictions_df["predicted_category"], 1, 0)
)

In [42]:
predictions_df["correct_prediction"].sum() / len(predictions_df)

np.float64(0.7630111524163569)

In [43]:
show_id =[]
predicted_cats = []

missing_cats = movies.loc[movies["simple_category"].isna(), ["show_id", "description"]].reset_index(drop=True)

In [44]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    show_id += [missing_cats["show_id"][i]]

100%|██████████| 7199/7199 [3:27:05<00:00,  1.73s/it]

In [45]:
missing_predictions_df = pd.DataFrame({"show_id1":show_id, "predicted_category": predicted_cats})

In [46]:
missing_predictions_df

      show_id1 predicted_category
0        10192            Fiction
1        27205         Nonfiction
2        12444         Nonfiction
3        38757            Fiction
4        10191         Nonfiction
...        ...                ...
7194    842924         Nonfiction
7195   1352077            Fiction
7196    934456         Nonfiction
7197   1254780            Fiction
7198   1405742         Nonfiction

[7199 rows x 2 columns]

merging with actual data with missing

In [55]:
movies = pd.merge(
    movies,
    missing_predictions_df,
    left_on="show_id",         # column in movies
    right_on="show_id1",       # column in missing_predictions_df
    how="left"
)
movies["simple_category"] = np.where(movies["simple_category"].isna(), movies["predicted_category"], movies["simple_category"])
movies = movies.drop(columns = ["predicted_category"])

In [76]:
movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,popularity,vote_count,vote_average,budget,revenue,tagged_description,simple_category,show_id1,predicted_category_x,predicted_category_y
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,...,203.893,7449,6.380,165000000,752600867,10192 A bored and domesticated Shrek pacts wit...,Fiction,10192.0,Fiction,Fiction
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,...,156.242,37119,8.369,160000000,839030630,"27205 Cobb, a skilled thief who commits corpor...",Nonfiction,27205.0,Nonfiction,Nonfiction
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,...,121.191,19327,7.744,250000000,954305868,"12444 Harry, Ron and Hermione walk away from t...",Nonfiction,12444.0,Nonfiction,Nonfiction
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,...,111.762,11638,7.600,260000000,592461732,"38757 Feisty teenager Rapunzel, who has long a...",Fiction,38757.0,Fiction,Fiction
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,...,110.044,13259,7.800,165000000,494879471,10191 As the son of a Viking leader on the cus...,Nonfiction,10191.0,Nonfiction,Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9285,934456,Movie,Americana,Tony Tost,"Sydney Sweeney, Paul Walter Hauser, Halsey, Si...","Canada, United States of America",2025-08-22,2025,0.000,NaN,...,4.968,0,0.000,0,0,934456 When a rare Lakota Ghost Shirt falls in...,Nonfiction,934456.0,Nonfiction,Nonfiction
9286,1254780,Movie,The Grove,"Acoryé White, Patrycja Kępa","Acoryé White, Carl Anthony Payne II, Psalms Sa...",United States of America,2025-04-04,2025,0.000,NaN,...,4.963,0,0.000,0,0,"1254780 When Terrance, a Black Ops soldier, go...",Fiction,1254780.0,Fiction,Fiction
9287,1424086,Movie,Blood and Stuffing,Ray Brown,"Hariclia Grammenou, Bethany Tickle, Ren, Ray B...",United Kingdom,2025-02-26,2025,0.000,NaN,...,4.953,0,0.000,0,0,1424086 A young girl plays a violent game afte...,Fiction,NaN,NaN,NaN
9288,1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,2025-03-13,2025,0.000,NaN,...,4.930,0,0.000,0,0,1271724 Poignant stories about men and women w...,Fiction,NaN,NaN,NaN
9289,1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2025-02-22,2025,0.000,NaN,...,4.921,0,0.000,0,0,1405742 After a debt-collector finds a portal ...,Nonfiction,1405742.0,Nonfiction,Nonfiction

In [78]:
movies = movies.drop(columns = ["predicted_category_x", "predicted_category_y"])

In [79]:
movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,language,description,popularity,vote_count,vote_average,budget,revenue,tagged_description,simple_category,show_id1
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,...,en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867,10192 A bored and domesticated Shrek pacts wit...,Fiction,10192.0
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,...,en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630,"27205 Cobb, a skilled thief who commits corpor...",Nonfiction,27205.0
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,...,en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868,"12444 Harry, Ron and Hermione walk away from t...",Nonfiction,12444.0
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,...,en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732,"38757 Feisty teenager Rapunzel, who has long a...",Fiction,38757.0
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,...,en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471,10191 As the son of a Viking leader on the cus...,Nonfiction,10191.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9285,934456,Movie,Americana,Tony Tost,"Sydney Sweeney, Paul Walter Hauser, Halsey, Si...","Canada, United States of America",2025-08-22,2025,0.000,NaN,...,en,When a rare Lakota Ghost Shirt falls into the ...,4.968,0,0.000,0,0,934456 When a rare Lakota Ghost Shirt falls in...,Nonfiction,934456.0
9286,1254780,Movie,The Grove,"Acoryé White, Patrycja Kępa","Acoryé White, Carl Anthony Payne II, Psalms Sa...",United States of America,2025-04-04,2025,0.000,NaN,...,en,"When Terrance, a Black Ops soldier, goes under...",4.963,0,0.000,0,0,"1254780 When Terrance, a Black Ops soldier, go...",Fiction,1254780.0
9287,1424086,Movie,Blood and Stuffing,Ray Brown,"Hariclia Grammenou, Bethany Tickle, Ren, Ray B...",United Kingdom,2025-02-26,2025,0.000,NaN,...,en,A young girl plays a violent game after her si...,4.953,0,0.000,0,0,1424086 A young girl plays a violent game afte...,Fiction,NaN
9288,1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,2025-03-13,2025,0.000,NaN,...,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0,0,1271724 Poignant stories about men and women w...,Fiction,NaN
9289,1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2025-02-22,2025,0.000,NaN,...,en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0,0,1405742 After a debt-collector finds a portal ...,Nonfiction,1405742.0

In [80]:
movies = pd.merge(movies, missing_predictions_df, on="show_id1", how="right")

In [81]:
movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,description,popularity,vote_count,vote_average,budget,revenue,tagged_description,simple_category,show_id1,predicted_category
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,...,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867,10192 A bored and domesticated Shrek pacts wit...,Fiction,10192.0,Fiction
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,...,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630,"27205 Cobb, a skilled thief who commits corpor...",Nonfiction,27205.0,Nonfiction
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,...,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868,"12444 Harry, Ron and Hermione walk away from t...",Nonfiction,12444.0,Nonfiction
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,...,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732,"38757 Feisty teenager Rapunzel, who has long a...",Fiction,38757.0,Fiction
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,...,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471,10191 As the son of a Viking leader on the cus...,Nonfiction,10191.0,Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7194,842924,Movie,The Life of Chuck,Mike Flanagan,"Tom Hiddleston, Mark Hamill, Chiwetel Ejiofor,...",United States of America,2025-05-30,2025,0.000,NaN,...,"A story told in reverse, starting with the end...",5.050,0,0.000,0,0,"842924 A story told in reverse, starting with ...",Nonfiction,842924.0,Nonfiction
7195,1352077,Movie,Verhängnisvolle Leidenschaft Sylt,Elmar Fischer,"Cornelia Gröschel, Artjom Gilz, Franz Dinda, L...",Germany,2025-01-31,2025,0.000,NaN,...,"After a drastic experience, Nina takes some ti...",5.030,0,0.000,0,0,"1352077 After a drastic experience, Nina takes...",Fiction,1352077.0,Fiction
7196,934456,Movie,Americana,Tony Tost,"Sydney Sweeney, Paul Walter Hauser, Halsey, Si...","Canada, United States of America",2025-08-22,2025,0.000,NaN,...,When a rare Lakota Ghost Shirt falls into the ...,4.968,0,0.000,0,0,934456 When a rare Lakota Ghost Shirt falls in...,Nonfiction,934456.0,Nonfiction
7197,1254780,Movie,The Grove,"Acoryé White, Patrycja Kępa","Acoryé White, Carl Anthony Payne II, Psalms Sa...",United States of America,2025-04-04,2025,0.000,NaN,...,"When Terrance, a Black Ops soldier, goes under...",4.963,0,0.000,0,0,"1254780 When Terrance, a Black Ops soldier, go...",Fiction,1254780.0,Fiction
7198,1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2025-02-22,2025,0.000,NaN,...,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0,0,1405742 After a debt-collector finds a portal ...,Nonfiction,1405742.0,Nonfiction

In [82]:
movies.to_csv("movies_with_categories.csv", index=False)